# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SoC_workspace/i2c/i2c.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
# IP: The module: 'system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SoC_workspace/i2c/i2c.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SoC_workspace/i2c/i2c.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/SoC_workspace/i2c/i2c.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
# IP: The module: 'system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SoC_workspace/i2c/i2c.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SoC_workspace/i2c/i2c.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
